apiVersion: v1
kind: Pod
metadata:
  name: antman-local-coordinator
  namespace: antman
spec:
  hostPID: true
  # hostIPC: true
  hostNetwork: true
  containers:
  - name: antman-local-coordinator
    # securityContext:
    #   privileged: true
    env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    image: lzxcn/local-coordinator:latest
    workingDir: /workspace
    command: ["sleep","3600"]
    resources:
      limits:
        memory: 2048Mi
      requests:
        cpu: 400m
        memory: 2048Mi
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: etcdpem
      mountPath: /etc/kubernetes/pki/etcd
      readOnly: true
    - name: antman
      mountPath: /tmp/antman
  # terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcdpem
    hostPath:
      path: /etc/kubernetes/pki/etcd
  - name: antman
    hostPath:
      path: /tmp/antman